apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruitments
  labels:
    app: recruitments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recruitments
  template:
    metadata:
      labels:
        app: recruitments
    spec:
      containers:
        - name: recruitments
          image: kvmayer/go-recruitments:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: recruitments
spec:
  selector:
    app: recruitments
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: grpc
