// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.5
// source: grpc-service/recruitment-service.proto

package grpc_service

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OrderDirection int32

const (
	OrderDirection_ASC  OrderDirection = 0
	OrderDirection_DESC OrderDirection = 1
)

// Enum value maps for OrderDirection.
var (
	OrderDirection_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	OrderDirection_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x OrderDirection) Enum() *OrderDirection {
	p := new(OrderDirection)
	*p = x
	return p
}

func (x OrderDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_service_recruitment_service_proto_enumTypes[0].Descriptor()
}

func (OrderDirection) Type() protoreflect.EnumType {
	return &file_grpc_service_recruitment_service_proto_enumTypes[0]
}

func (x OrderDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderDirection.Descriptor instead.
func (OrderDirection) EnumDescriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{0}
}

type Vacancy_Status int32

const (
	Vacancy_PENDING  Vacancy_Status = 0
	Vacancy_AGREED   Vacancy_Status = 1
	Vacancy_REJECTED Vacancy_Status = 2
	Vacancy_IN_WORK  Vacancy_Status = 3
	Vacancy_CLOSED   Vacancy_Status = 4
)

// Enum value maps for Vacancy_Status.
var (
	Vacancy_Status_name = map[int32]string{
		0: "PENDING",
		1: "AGREED",
		2: "REJECTED",
		3: "IN_WORK",
		4: "CLOSED",
	}
	Vacancy_Status_value = map[string]int32{
		"PENDING":  0,
		"AGREED":   1,
		"REJECTED": 2,
		"IN_WORK":  3,
		"CLOSED":   4,
	}
)

func (x Vacancy_Status) Enum() *Vacancy_Status {
	p := new(Vacancy_Status)
	*p = x
	return p
}

func (x Vacancy_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Vacancy_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_service_recruitment_service_proto_enumTypes[1].Descriptor()
}

func (Vacancy_Status) Type() protoreflect.EnumType {
	return &file_grpc_service_recruitment_service_proto_enumTypes[1]
}

func (x Vacancy_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Vacancy_Status.Descriptor instead.
func (Vacancy_Status) EnumDescriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{24, 0}
}

type Vacancy_Order int32

const (
	Vacancy_CREATED_AT Vacancy_Order = 0
)

// Enum value maps for Vacancy_Order.
var (
	Vacancy_Order_name = map[int32]string{
		0: "CREATED_AT",
	}
	Vacancy_Order_value = map[string]int32{
		"CREATED_AT": 0,
	}
)

func (x Vacancy_Order) Enum() *Vacancy_Order {
	p := new(Vacancy_Order)
	*p = x
	return p
}

func (x Vacancy_Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Vacancy_Order) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_service_recruitment_service_proto_enumTypes[2].Descriptor()
}

func (Vacancy_Order) Type() protoreflect.EnumType {
	return &file_grpc_service_recruitment_service_proto_enumTypes[2]
}

func (x Vacancy_Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Vacancy_Order.Descriptor instead.
func (Vacancy_Order) EnumDescriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{24, 1}
}

type Recruitment_Order int32

const (
	Recruitment_CREATED_AT Recruitment_Order = 0
)

// Enum value maps for Recruitment_Order.
var (
	Recruitment_Order_name = map[int32]string{
		0: "CREATED_AT",
	}
	Recruitment_Order_value = map[string]int32{
		"CREATED_AT": 0,
	}
)

func (x Recruitment_Order) Enum() *Recruitment_Order {
	p := new(Recruitment_Order)
	*p = x
	return p
}

func (x Recruitment_Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Recruitment_Order) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_service_recruitment_service_proto_enumTypes[3].Descriptor()
}

func (Recruitment_Order) Type() protoreflect.EnumType {
	return &file_grpc_service_recruitment_service_proto_enumTypes[3]
}

func (x Recruitment_Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Recruitment_Order.Descriptor instead.
func (Recruitment_Order) EnumDescriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{25, 0}
}

type PostVacancyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PositionId string `protobuf:"bytes,1,opt,name=positionId,proto3" json:"positionId,omitempty"`
	CustomerId string `protobuf:"bytes,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
}

func (x *PostVacancyRequest) Reset() {
	*x = PostVacancyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostVacancyRequest) ProtoMessage() {}

func (x *PostVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostVacancyRequest.ProtoReflect.Descriptor instead.
func (*PostVacancyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{0}
}

func (x *PostVacancyRequest) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *PostVacancyRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type PostVacancyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VacancyId string `protobuf:"bytes,1,opt,name=vacancyId,proto3" json:"vacancyId,omitempty"`
}

func (x *PostVacancyResponse) Reset() {
	*x = PostVacancyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostVacancyResponse) ProtoMessage() {}

func (x *PostVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostVacancyResponse.ProtoReflect.Descriptor instead.
func (*PostVacancyResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{1}
}

func (x *PostVacancyResponse) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

type ShowVacanciesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId     string         `protobuf:"bytes,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Page           int32          `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size           int32          `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	OrderBy        Vacancy_Order  `protobuf:"varint,4,opt,name=orderBy,proto3,enum=Vacancy_Order" json:"orderBy,omitempty"`
	OrderDirection OrderDirection `protobuf:"varint,5,opt,name=orderDirection,proto3,enum=OrderDirection" json:"orderDirection,omitempty"`
}

func (x *ShowVacanciesRequest) Reset() {
	*x = ShowVacanciesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowVacanciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowVacanciesRequest) ProtoMessage() {}

func (x *ShowVacanciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowVacanciesRequest.ProtoReflect.Descriptor instead.
func (*ShowVacanciesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{2}
}

func (x *ShowVacanciesRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ShowVacanciesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ShowVacanciesRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ShowVacanciesRequest) GetOrderBy() Vacancy_Order {
	if x != nil {
		return x.OrderBy
	}
	return Vacancy_CREATED_AT
}

func (x *ShowVacanciesRequest) GetOrderDirection() OrderDirection {
	if x != nil {
		return x.OrderDirection
	}
	return OrderDirection_ASC
}

type ShowVacanciesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*Vacancy `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Count int32      `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ShowVacanciesResponse) Reset() {
	*x = ShowVacanciesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowVacanciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowVacanciesResponse) ProtoMessage() {}

func (x *ShowVacanciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowVacanciesResponse.ProtoReflect.Descriptor instead.
func (*ShowVacanciesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{3}
}

func (x *ShowVacanciesResponse) GetList() []*Vacancy {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ShowVacanciesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SearchVacanciesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page           int32          `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size           int32          `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	OrderBy        Vacancy_Order  `protobuf:"varint,3,opt,name=orderBy,proto3,enum=Vacancy_Order" json:"orderBy,omitempty"`
	OrderDirection OrderDirection `protobuf:"varint,4,opt,name=orderDirection,proto3,enum=OrderDirection" json:"orderDirection,omitempty"`
}

func (x *SearchVacanciesRequest) Reset() {
	*x = SearchVacanciesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchVacanciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVacanciesRequest) ProtoMessage() {}

func (x *SearchVacanciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVacanciesRequest.ProtoReflect.Descriptor instead.
func (*SearchVacanciesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{4}
}

func (x *SearchVacanciesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchVacanciesRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchVacanciesRequest) GetOrderBy() Vacancy_Order {
	if x != nil {
		return x.OrderBy
	}
	return Vacancy_CREATED_AT
}

func (x *SearchVacanciesRequest) GetOrderDirection() OrderDirection {
	if x != nil {
		return x.OrderDirection
	}
	return OrderDirection_ASC
}

type SearchVacanciesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*Vacancy `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Count int32      `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *SearchVacanciesResponse) Reset() {
	*x = SearchVacanciesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchVacanciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVacanciesResponse) ProtoMessage() {}

func (x *SearchVacanciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVacanciesResponse.ProtoReflect.Descriptor instead.
func (*SearchVacanciesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{5}
}

func (x *SearchVacanciesResponse) GetList() []*Vacancy {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *SearchVacanciesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ConsiderCandidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VacancyId     string               `protobuf:"bytes,1,opt,name=vacancyId,proto3" json:"vacancyId,omitempty"`
	CandidateId   string               `protobuf:"bytes,2,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	ResponsibleId string               `protobuf:"bytes,3,opt,name=responsibleId,proto3" json:"responsibleId,omitempty"`
	Settings      []*StageLineSettings `protobuf:"bytes,4,rep,name=settings,proto3" json:"settings,omitempty"`
}

func (x *ConsiderCandidateRequest) Reset() {
	*x = ConsiderCandidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsiderCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsiderCandidateRequest) ProtoMessage() {}

func (x *ConsiderCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsiderCandidateRequest.ProtoReflect.Descriptor instead.
func (*ConsiderCandidateRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{6}
}

func (x *ConsiderCandidateRequest) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

func (x *ConsiderCandidateRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *ConsiderCandidateRequest) GetResponsibleId() string {
	if x != nil {
		return x.ResponsibleId
	}
	return ""
}

func (x *ConsiderCandidateRequest) GetSettings() []*StageLineSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ConsiderCandidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecruitmentId string `protobuf:"bytes,1,opt,name=recruitmentId,proto3" json:"recruitmentId,omitempty"`
}

func (x *ConsiderCandidateResponse) Reset() {
	*x = ConsiderCandidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsiderCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsiderCandidateResponse) ProtoMessage() {}

func (x *ConsiderCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsiderCandidateResponse.ProtoReflect.Descriptor instead.
func (*ConsiderCandidateResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{7}
}

func (x *ConsiderCandidateResponse) GetRecruitmentId() string {
	if x != nil {
		return x.RecruitmentId
	}
	return ""
}

type AcceptRecruitmentStageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecruitmentId    string `protobuf:"bytes,1,opt,name=recruitmentId,proto3" json:"recruitmentId,omitempty"`
	RequestedStageId string `protobuf:"bytes,2,opt,name=requestedStageId,proto3" json:"requestedStageId,omitempty"`
}

func (x *AcceptRecruitmentStageRequest) Reset() {
	*x = AcceptRecruitmentStageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptRecruitmentStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRecruitmentStageRequest) ProtoMessage() {}

func (x *AcceptRecruitmentStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRecruitmentStageRequest.ProtoReflect.Descriptor instead.
func (*AcceptRecruitmentStageRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptRecruitmentStageRequest) GetRecruitmentId() string {
	if x != nil {
		return x.RecruitmentId
	}
	return ""
}

func (x *AcceptRecruitmentStageRequest) GetRequestedStageId() string {
	if x != nil {
		return x.RequestedStageId
	}
	return ""
}

type DenyRecruitmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecruitmentId string        `protobuf:"bytes,1,opt,name=recruitmentId,proto3" json:"recruitmentId,omitempty"`
	Reason        *RefuseReason `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *DenyRecruitmentRequest) Reset() {
	*x = DenyRecruitmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DenyRecruitmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyRecruitmentRequest) ProtoMessage() {}

func (x *DenyRecruitmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyRecruitmentRequest.ProtoReflect.Descriptor instead.
func (*DenyRecruitmentRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{9}
}

func (x *DenyRecruitmentRequest) GetRecruitmentId() string {
	if x != nil {
		return x.RecruitmentId
	}
	return ""
}

func (x *DenyRecruitmentRequest) GetReason() *RefuseReason {
	if x != nil {
		return x.Reason
	}
	return nil
}

type ChangeVacancyPositionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VacancyId  string `protobuf:"bytes,1,opt,name=vacancyId,proto3" json:"vacancyId,omitempty"`
	PositionId string `protobuf:"bytes,2,opt,name=positionId,proto3" json:"positionId,omitempty"`
}

func (x *ChangeVacancyPositionRequest) Reset() {
	*x = ChangeVacancyPositionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeVacancyPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeVacancyPositionRequest) ProtoMessage() {}

func (x *ChangeVacancyPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeVacancyPositionRequest.ProtoReflect.Descriptor instead.
func (*ChangeVacancyPositionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeVacancyPositionRequest) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

func (x *ChangeVacancyPositionRequest) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{11}
}

type ApproveVacancyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VacancyId string `protobuf:"bytes,1,opt,name=vacancyId,proto3" json:"vacancyId,omitempty"`
}

func (x *ApproveVacancyRequest) Reset() {
	*x = ApproveVacancyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApproveVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveVacancyRequest) ProtoMessage() {}

func (x *ApproveVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveVacancyRequest.ProtoReflect.Descriptor instead.
func (*ApproveVacancyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{12}
}

func (x *ApproveVacancyRequest) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

type CloseVacancyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VacancyId string `protobuf:"bytes,1,opt,name=vacancyId,proto3" json:"vacancyId,omitempty"`
}

func (x *CloseVacancyRequest) Reset() {
	*x = CloseVacancyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseVacancyRequest) ProtoMessage() {}

func (x *CloseVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseVacancyRequest.ProtoReflect.Descriptor instead.
func (*CloseVacancyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{13}
}

func (x *CloseVacancyRequest) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

type RejectVacancyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VacancyId string `protobuf:"bytes,1,opt,name=vacancyId,proto3" json:"vacancyId,omitempty"`
}

func (x *RejectVacancyRequest) Reset() {
	*x = RejectVacancyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejectVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectVacancyRequest) ProtoMessage() {}

func (x *RejectVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectVacancyRequest.ProtoReflect.Descriptor instead.
func (*RejectVacancyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{14}
}

func (x *RejectVacancyRequest) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

type TakeInWorkVacancyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VacancyId string `protobuf:"bytes,1,opt,name=vacancyId,proto3" json:"vacancyId,omitempty"`
}

func (x *TakeInWorkVacancyRequest) Reset() {
	*x = TakeInWorkVacancyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TakeInWorkVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeInWorkVacancyRequest) ProtoMessage() {}

func (x *TakeInWorkVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeInWorkVacancyRequest.ProtoReflect.Descriptor instead.
func (*TakeInWorkVacancyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{15}
}

func (x *TakeInWorkVacancyRequest) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

type ConsiderCandidateAnotherVacancyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecruitmentId string               `protobuf:"bytes,1,opt,name=recruitmentId,proto3" json:"recruitmentId,omitempty"`
	VacancyId     string               `protobuf:"bytes,2,opt,name=vacancyId,proto3" json:"vacancyId,omitempty"`
	Settings      []*StageLineSettings `protobuf:"bytes,3,rep,name=settings,proto3" json:"settings,omitempty"`
}

func (x *ConsiderCandidateAnotherVacancyRequest) Reset() {
	*x = ConsiderCandidateAnotherVacancyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsiderCandidateAnotherVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsiderCandidateAnotherVacancyRequest) ProtoMessage() {}

func (x *ConsiderCandidateAnotherVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsiderCandidateAnotherVacancyRequest.ProtoReflect.Descriptor instead.
func (*ConsiderCandidateAnotherVacancyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{16}
}

func (x *ConsiderCandidateAnotherVacancyRequest) GetRecruitmentId() string {
	if x != nil {
		return x.RecruitmentId
	}
	return ""
}

func (x *ConsiderCandidateAnotherVacancyRequest) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

func (x *ConsiderCandidateAnotherVacancyRequest) GetSettings() []*StageLineSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ConsiderCandidateAnotherVacancyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecruitmentId string `protobuf:"bytes,1,opt,name=recruitmentId,proto3" json:"recruitmentId,omitempty"`
}

func (x *ConsiderCandidateAnotherVacancyResponse) Reset() {
	*x = ConsiderCandidateAnotherVacancyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsiderCandidateAnotherVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsiderCandidateAnotherVacancyResponse) ProtoMessage() {}

func (x *ConsiderCandidateAnotherVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsiderCandidateAnotherVacancyResponse.ProtoReflect.Descriptor instead.
func (*ConsiderCandidateAnotherVacancyResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{17}
}

func (x *ConsiderCandidateAnotherVacancyResponse) GetRecruitmentId() string {
	if x != nil {
		return x.RecruitmentId
	}
	return ""
}

type GetVacancyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VacancyId string `protobuf:"bytes,1,opt,name=vacancyId,proto3" json:"vacancyId,omitempty"`
}

func (x *GetVacancyRequest) Reset() {
	*x = GetVacancyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVacancyRequest) ProtoMessage() {}

func (x *GetVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVacancyRequest.ProtoReflect.Descriptor instead.
func (*GetVacancyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetVacancyRequest) GetVacancyId() string {
	if x != nil {
		return x.VacancyId
	}
	return ""
}

type GetVacancyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vacancy *Vacancy `protobuf:"bytes,1,opt,name=vacancy,proto3" json:"vacancy,omitempty"`
}

func (x *GetVacancyResponse) Reset() {
	*x = GetVacancyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVacancyResponse) ProtoMessage() {}

func (x *GetVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVacancyResponse.ProtoReflect.Descriptor instead.
func (*GetVacancyResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetVacancyResponse) GetVacancy() *Vacancy {
	if x != nil {
		return x.Vacancy
	}
	return nil
}

type GetRecruitmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecruitmentId string `protobuf:"bytes,1,opt,name=recruitmentId,proto3" json:"recruitmentId,omitempty"`
}

func (x *GetRecruitmentRequest) Reset() {
	*x = GetRecruitmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecruitmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecruitmentRequest) ProtoMessage() {}

func (x *GetRecruitmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecruitmentRequest.ProtoReflect.Descriptor instead.
func (*GetRecruitmentRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetRecruitmentRequest) GetRecruitmentId() string {
	if x != nil {
		return x.RecruitmentId
	}
	return ""
}

type GetRecruitmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recruitment *Recruitment `protobuf:"bytes,1,opt,name=recruitment,proto3" json:"recruitment,omitempty"`
}

func (x *GetRecruitmentResponse) Reset() {
	*x = GetRecruitmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecruitmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecruitmentResponse) ProtoMessage() {}

func (x *GetRecruitmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecruitmentResponse.ProtoReflect.Descriptor instead.
func (*GetRecruitmentResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetRecruitmentResponse) GetRecruitment() *Recruitment {
	if x != nil {
		return x.Recruitment
	}
	return nil
}

type ShowRecruitmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponsibleId  string            `protobuf:"bytes,1,opt,name=responsibleId,proto3" json:"responsibleId,omitempty"`
	Page           int32             `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size           int32             `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	OrderBy        Recruitment_Order `protobuf:"varint,4,opt,name=orderBy,proto3,enum=Recruitment_Order" json:"orderBy,omitempty"`
	OrderDirection OrderDirection    `protobuf:"varint,5,opt,name=orderDirection,proto3,enum=OrderDirection" json:"orderDirection,omitempty"`
}

func (x *ShowRecruitmentRequest) Reset() {
	*x = ShowRecruitmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowRecruitmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowRecruitmentRequest) ProtoMessage() {}

func (x *ShowRecruitmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowRecruitmentRequest.ProtoReflect.Descriptor instead.
func (*ShowRecruitmentRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{22}
}

func (x *ShowRecruitmentRequest) GetResponsibleId() string {
	if x != nil {
		return x.ResponsibleId
	}
	return ""
}

func (x *ShowRecruitmentRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ShowRecruitmentRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ShowRecruitmentRequest) GetOrderBy() Recruitment_Order {
	if x != nil {
		return x.OrderBy
	}
	return Recruitment_CREATED_AT
}

func (x *ShowRecruitmentRequest) GetOrderDirection() OrderDirection {
	if x != nil {
		return x.OrderDirection
	}
	return OrderDirection_ASC
}

type ShowRecruitmentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*Recruitment `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Count int32          `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ShowRecruitmentsResponse) Reset() {
	*x = ShowRecruitmentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowRecruitmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowRecruitmentsResponse) ProtoMessage() {}

func (x *ShowRecruitmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowRecruitmentsResponse.ProtoReflect.Descriptor instead.
func (*ShowRecruitmentsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{23}
}

func (x *ShowRecruitmentsResponse) GetList() []*Recruitment {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ShowRecruitmentsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Vacancy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PositionId string         `protobuf:"bytes,2,opt,name=positionId,proto3" json:"positionId,omitempty"`
	CustomerId string         `protobuf:"bytes,3,opt,name=customerId,proto3" json:"customerId,omitempty"`
	CreatedAt  string         `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Status     Vacancy_Status `protobuf:"varint,5,opt,name=status,proto3,enum=Vacancy_Status" json:"status,omitempty"`
}

func (x *Vacancy) Reset() {
	*x = Vacancy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vacancy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacancy) ProtoMessage() {}

func (x *Vacancy) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacancy.ProtoReflect.Descriptor instead.
func (*Vacancy) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{24}
}

func (x *Vacancy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vacancy) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *Vacancy) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Vacancy) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Vacancy) GetStatus() Vacancy_Status {
	if x != nil {
		return x.Status
	}
	return Vacancy_PENDING
}

type Recruitment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CandidateId   string        `protobuf:"bytes,2,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	ResponsibleId string        `protobuf:"bytes,3,opt,name=responsibleId,proto3" json:"responsibleId,omitempty"`
	CreatedAt     string        `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	StageLine     *StageLine    `protobuf:"bytes,5,opt,name=stageLine,proto3" json:"stageLine,omitempty"`
	Vacancy       *Vacancy      `protobuf:"bytes,6,opt,name=vacancy,proto3" json:"vacancy,omitempty"`
	RefuseReason  *RefuseReason `protobuf:"bytes,7,opt,name=refuseReason,proto3" json:"refuseReason,omitempty"`
}

func (x *Recruitment) Reset() {
	*x = Recruitment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Recruitment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recruitment) ProtoMessage() {}

func (x *Recruitment) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recruitment.ProtoReflect.Descriptor instead.
func (*Recruitment) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{25}
}

func (x *Recruitment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Recruitment) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *Recruitment) GetResponsibleId() string {
	if x != nil {
		return x.ResponsibleId
	}
	return ""
}

func (x *Recruitment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Recruitment) GetStageLine() *StageLine {
	if x != nil {
		return x.StageLine
	}
	return nil
}

func (x *Recruitment) GetVacancy() *Vacancy {
	if x != nil {
		return x.Vacancy
	}
	return nil
}

func (x *Recruitment) GetRefuseReason() *RefuseReason {
	if x != nil {
		return x.RefuseReason
	}
	return nil
}

type StageLineSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StageId              string `protobuf:"bytes,1,opt,name=stageId,proto3" json:"stageId,omitempty"`
	DeadlineDurationSec  int32  `protobuf:"varint,2,opt,name=DeadlineDurationSec,proto3" json:"DeadlineDurationSec,omitempty"`
	ThresholdDurationSec int32  `protobuf:"varint,3,opt,name=ThresholdDurationSec,proto3" json:"ThresholdDurationSec,omitempty"`
}

func (x *StageLineSettings) Reset() {
	*x = StageLineSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageLineSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageLineSettings) ProtoMessage() {}

func (x *StageLineSettings) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageLineSettings.ProtoReflect.Descriptor instead.
func (*StageLineSettings) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{26}
}

func (x *StageLineSettings) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *StageLineSettings) GetDeadlineDurationSec() int32 {
	if x != nil {
		return x.DeadlineDurationSec
	}
	return 0
}

func (x *StageLineSettings) GetThresholdDurationSec() int32 {
	if x != nil {
		return x.ThresholdDurationSec
	}
	return 0
}

type StageLineItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StageId       string `protobuf:"bytes,1,opt,name=stageId,proto3" json:"stageId,omitempty"`
	StartDate     string `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	FinishDate    string `protobuf:"bytes,3,opt,name=finishDate,proto3" json:"finishDate,omitempty"`
	DeadlineDate  string `protobuf:"bytes,4,opt,name=DeadlineDate,proto3" json:"DeadlineDate,omitempty"`
	ThresholdDate string `protobuf:"bytes,5,opt,name=ThresholdDate,proto3" json:"ThresholdDate,omitempty"`
}

func (x *StageLineItem) Reset() {
	*x = StageLineItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageLineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageLineItem) ProtoMessage() {}

func (x *StageLineItem) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageLineItem.ProtoReflect.Descriptor instead.
func (*StageLineItem) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{27}
}

func (x *StageLineItem) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *StageLineItem) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *StageLineItem) GetFinishDate() string {
	if x != nil {
		return x.FinishDate
	}
	return ""
}

func (x *StageLineItem) GetDeadlineDate() string {
	if x != nil {
		return x.DeadlineDate
	}
	return ""
}

func (x *StageLineItem) GetThresholdDate() string {
	if x != nil {
		return x.ThresholdDate
	}
	return ""
}

type StageLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StageId  string                    `protobuf:"bytes,1,opt,name=stageId,proto3" json:"stageId,omitempty"`
	Settings []*StageLineSettings      `protobuf:"bytes,2,rep,name=settings,proto3" json:"settings,omitempty"`
	History  map[string]*StageLineItem `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *StageLine) Reset() {
	*x = StageLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageLine) ProtoMessage() {}

func (x *StageLine) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageLine.ProtoReflect.Descriptor instead.
func (*StageLine) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{28}
}

func (x *StageLine) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *StageLine) GetSettings() []*StageLineSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *StageLine) GetHistory() map[string]*StageLineItem {
	if x != nil {
		return x.History
	}
	return nil
}

type RefuseReason struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReasonId string `protobuf:"bytes,1,opt,name=reasonId,proto3" json:"reasonId,omitempty"`
	Comment  string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *RefuseReason) Reset() {
	*x = RefuseReason{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_service_recruitment_service_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefuseReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefuseReason) ProtoMessage() {}

func (x *RefuseReason) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_recruitment_service_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefuseReason.ProtoReflect.Descriptor instead.
func (*RefuseReason) Descriptor() ([]byte, []int) {
	return file_grpc_service_recruitment_service_proto_rawDescGZIP(), []int{29}
}

func (x *RefuseReason) GetReasonId() string {
	if x != nil {
		return x.ReasonId
	}
	return ""
}

func (x *RefuseReason) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

var File_grpc_service_recruitment_service_proto protoreflect.FileDescriptor

var file_grpc_service_recruitment_service_proto_rawDesc = []byte{
	0x0a, 0x26, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x72,
	0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x12, 0x50, 0x6f, 0x73, 0x74,
	0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x22, 0x33,
	0x0a, 0x13, 0x50, 0x6f, 0x73, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63,
	0x79, 0x49, 0x64, 0x22, 0xc1, 0x01, 0x0a, 0x14, 0x53, 0x68, 0x6f, 0x77, 0x56, 0x61, 0x63, 0x61,
	0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x12, 0x37,
	0x0a, 0x0e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4b, 0x0a, 0x15, 0x53, 0x68, 0x6f, 0x77, 0x56,
	0x61, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0xa3, 0x01, 0x0a, 0x16, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56,
	0x61, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x42, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x56, 0x61, 0x63, 0x61, 0x6e,
	0x63, 0x79, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42,
	0x79, 0x12, 0x37, 0x0a, 0x0e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x17, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xb0, 0x01, 0x0a, 0x18, 0x43, 0x6f,
	0x6e, 0x73, 0x69, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63,
	0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e,
	0x63, 0x79, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x6e, 0x64, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x69, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x08,
	0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x41, 0x0a, 0x19,
	0x43, 0x6f, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x63,
	0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x71, 0x0a, 0x1d, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x49, 0x64, 0x22, 0x65, 0x0a, 0x16, 0x44, 0x65, 0x6e, 0x79, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d,
	0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x25, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x73, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x5c, 0x0a, 0x1c, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x63,
	0x61, 0x6e, 0x63, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61,
	0x63, 0x61, 0x6e, 0x63, 0x79, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x35, 0x0a, 0x15, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e,
	0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x63,
	0x61, 0x6e, 0x63, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61,
	0x63, 0x61, 0x6e, 0x63, 0x79, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x13, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x14,
	0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79,
	0x49, 0x64, 0x22, 0x38, 0x0a, 0x18, 0x54, 0x61, 0x6b, 0x65, 0x49, 0x6e, 0x57, 0x6f, 0x72, 0x6b,
	0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x49, 0x64, 0x22, 0x9c, 0x01, 0x0a,
	0x26, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x72, 0x75,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x08, 0x73,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x53, 0x74, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x4f, 0x0a, 0x27, 0x43,
	0x6f, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72,
	0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x49, 0x64, 0x22,
	0x38, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79,
	0x52, 0x07, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x22, 0x3d, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x72, 0x75,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0xcd, 0x01, 0x0a, 0x16, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x63, 0x72, 0x75,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a,
	0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x69, 0x62, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x52,
	0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x12, 0x37, 0x0a, 0x0e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x52, 0x0a, 0x18, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x52,
	0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x83, 0x02, 0x0a, 0x07, 0x56, 0x61, 0x63, 0x61, 0x6e,
	0x63, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x48, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x41, 0x47, 0x52, 0x45, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e,
	0x5f, 0x57, 0x4f, 0x52, 0x4b, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4c, 0x4f, 0x53, 0x45,
	0x44, 0x10, 0x04, 0x22, 0x17, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x0a,
	0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x5f, 0x41, 0x54, 0x10, 0x00, 0x22, 0x9d, 0x02, 0x0a,
	0x0b, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x24,
	0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x69, 0x62,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x28, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e,
	0x65, 0x52, 0x09, 0x73, 0x74, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x22, 0x0a, 0x07,
	0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x07, 0x76, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79,
	0x12, 0x31, 0x0a, 0x0c, 0x72, 0x65, 0x66, 0x75, 0x73, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x73, 0x65, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x75, 0x73, 0x65, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x22, 0x17, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x0a,
	0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x5f, 0x41, 0x54, 0x10, 0x00, 0x22, 0x93, 0x01, 0x0a,
	0x11, 0x53, 0x74, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x13,
	0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x44, 0x65, 0x61, 0x64, 0x6c,
	0x69, 0x6e, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x12, 0x32,
	0x0a, 0x14, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x54, 0x68,
	0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x63, 0x22, 0xb1, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x44, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x44, 0x61, 0x74,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f,
	0x6c, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0xd4, 0x01, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x4c, 0x69, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x2e,
	0x0a, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x31,
	0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x2e, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x1a, 0x4a, 0x0a, 0x0c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x44, 0x0a,
	0x0c, 0x52, 0x65, 0x66, 0x75, 0x73, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x2a, 0x23, 0x0a, 0x0e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x53, 0x43, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x44, 0x45, 0x53, 0x43, 0x10, 0x01, 0x32, 0xf4, 0x07, 0x0a, 0x12, 0x52, 0x65, 0x63,
	0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3a, 0x0a, 0x0b, 0x50, 0x6f, 0x73, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x13,
	0x2e, 0x50, 0x6f, 0x73, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x53,
	0x68, 0x6f, 0x77, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x53,
	0x68, 0x6f, 0x77, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a,
	0x0f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x65, 0x73,
	0x12, 0x17, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x56,
	0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x16, 0x2e, 0x41, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0c, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x14, 0x2e, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0d, 0x52,
	0x65, 0x6a, 0x65, 0x63, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x15, 0x2e, 0x52,
	0x65, 0x6a, 0x65, 0x63, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x38, 0x0a,
	0x11, 0x54, 0x61, 0x6b, 0x65, 0x49, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x56, 0x61, 0x63, 0x61, 0x6e,
	0x63, 0x79, 0x12, 0x19, 0x2e, 0x54, 0x61, 0x6b, 0x65, 0x49, 0x6e, 0x57, 0x6f, 0x72, 0x6b, 0x56,
	0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x56, 0x61,
	0x63, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e,
	0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x56,
	0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4c, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x72,
	0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x64, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x76,
	0x0a, 0x1f, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63,
	0x79, 0x12, 0x27, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x56, 0x61, 0x63, 0x61,
	0x6e, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x43, 0x6f, 0x6e,
	0x73, 0x69, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e,
	0x6f, 0x74, 0x68, 0x65, 0x72, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x16, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x12, 0x1e, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0f, 0x44, 0x65,
	0x6e, 0x79, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e,
	0x44, 0x65, 0x6e, 0x79, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x43, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x63,
	0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x17, 0x2e, 0x53, 0x68, 0x6f, 0x77,
	0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61,
	0x79, 0x65, 0x72, 0x6b, 0x76, 0x2f, 0x67, 0x6f, 0x2d, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_service_recruitment_service_proto_rawDescOnce sync.Once
	file_grpc_service_recruitment_service_proto_rawDescData = file_grpc_service_recruitment_service_proto_rawDesc
)

func file_grpc_service_recruitment_service_proto_rawDescGZIP() []byte {
	file_grpc_service_recruitment_service_proto_rawDescOnce.Do(func() {
		file_grpc_service_recruitment_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_service_recruitment_service_proto_rawDescData)
	})
	return file_grpc_service_recruitment_service_proto_rawDescData
}

var file_grpc_service_recruitment_service_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_grpc_service_recruitment_service_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_grpc_service_recruitment_service_proto_goTypes = []interface{}{
	(OrderDirection)(0),                             // 0: OrderDirection
	(Vacancy_Status)(0),                             // 1: Vacancy.Status
	(Vacancy_Order)(0),                              // 2: Vacancy.Order
	(Recruitment_Order)(0),                          // 3: Recruitment.Order
	(*PostVacancyRequest)(nil),                      // 4: PostVacancyRequest
	(*PostVacancyResponse)(nil),                     // 5: PostVacancyResponse
	(*ShowVacanciesRequest)(nil),                    // 6: ShowVacanciesRequest
	(*ShowVacanciesResponse)(nil),                   // 7: ShowVacanciesResponse
	(*SearchVacanciesRequest)(nil),                  // 8: SearchVacanciesRequest
	(*SearchVacanciesResponse)(nil),                 // 9: SearchVacanciesResponse
	(*ConsiderCandidateRequest)(nil),                // 10: ConsiderCandidateRequest
	(*ConsiderCandidateResponse)(nil),               // 11: ConsiderCandidateResponse
	(*AcceptRecruitmentStageRequest)(nil),           // 12: AcceptRecruitmentStageRequest
	(*DenyRecruitmentRequest)(nil),                  // 13: DenyRecruitmentRequest
	(*ChangeVacancyPositionRequest)(nil),            // 14: ChangeVacancyPositionRequest
	(*Empty)(nil),                                   // 15: Empty
	(*ApproveVacancyRequest)(nil),                   // 16: ApproveVacancyRequest
	(*CloseVacancyRequest)(nil),                     // 17: CloseVacancyRequest
	(*RejectVacancyRequest)(nil),                    // 18: RejectVacancyRequest
	(*TakeInWorkVacancyRequest)(nil),                // 19: TakeInWorkVacancyRequest
	(*ConsiderCandidateAnotherVacancyRequest)(nil),  // 20: ConsiderCandidateAnotherVacancyRequest
	(*ConsiderCandidateAnotherVacancyResponse)(nil), // 21: ConsiderCandidateAnotherVacancyResponse
	(*GetVacancyRequest)(nil),                       // 22: GetVacancyRequest
	(*GetVacancyResponse)(nil),                      // 23: GetVacancyResponse
	(*GetRecruitmentRequest)(nil),                   // 24: GetRecruitmentRequest
	(*GetRecruitmentResponse)(nil),                  // 25: GetRecruitmentResponse
	(*ShowRecruitmentRequest)(nil),                  // 26: ShowRecruitmentRequest
	(*ShowRecruitmentsResponse)(nil),                // 27: ShowRecruitmentsResponse
	(*Vacancy)(nil),                                 // 28: Vacancy
	(*Recruitment)(nil),                             // 29: Recruitment
	(*StageLineSettings)(nil),                       // 30: StageLineSettings
	(*StageLineItem)(nil),                           // 31: StageLineItem
	(*StageLine)(nil),                               // 32: StageLine
	(*RefuseReason)(nil),                            // 33: RefuseReason
	nil,                                             // 34: StageLine.HistoryEntry
}
var file_grpc_service_recruitment_service_proto_depIdxs = []int32{
	2,  // 0: ShowVacanciesRequest.orderBy:type_name -> Vacancy.Order
	0,  // 1: ShowVacanciesRequest.orderDirection:type_name -> OrderDirection
	28, // 2: ShowVacanciesResponse.list:type_name -> Vacancy
	2,  // 3: SearchVacanciesRequest.orderBy:type_name -> Vacancy.Order
	0,  // 4: SearchVacanciesRequest.orderDirection:type_name -> OrderDirection
	28, // 5: SearchVacanciesResponse.list:type_name -> Vacancy
	30, // 6: ConsiderCandidateRequest.settings:type_name -> StageLineSettings
	33, // 7: DenyRecruitmentRequest.reason:type_name -> RefuseReason
	30, // 8: ConsiderCandidateAnotherVacancyRequest.settings:type_name -> StageLineSettings
	28, // 9: GetVacancyResponse.vacancy:type_name -> Vacancy
	29, // 10: GetRecruitmentResponse.recruitment:type_name -> Recruitment
	3,  // 11: ShowRecruitmentRequest.orderBy:type_name -> Recruitment.Order
	0,  // 12: ShowRecruitmentRequest.orderDirection:type_name -> OrderDirection
	29, // 13: ShowRecruitmentsResponse.list:type_name -> Recruitment
	1,  // 14: Vacancy.status:type_name -> Vacancy.Status
	32, // 15: Recruitment.stageLine:type_name -> StageLine
	28, // 16: Recruitment.vacancy:type_name -> Vacancy
	33, // 17: Recruitment.refuseReason:type_name -> RefuseReason
	30, // 18: StageLine.settings:type_name -> StageLineSettings
	34, // 19: StageLine.history:type_name -> StageLine.HistoryEntry
	31, // 20: StageLine.HistoryEntry.value:type_name -> StageLineItem
	4,  // 21: RecruitmentService.PostVacancy:input_type -> PostVacancyRequest
	6,  // 22: RecruitmentService.ShowVacancies:input_type -> ShowVacanciesRequest
	8,  // 23: RecruitmentService.SearchVacancies:input_type -> SearchVacanciesRequest
	14, // 24: RecruitmentService.ChangeVacancyPosition:input_type -> ChangeVacancyPositionRequest
	16, // 25: RecruitmentService.ApproveVacancy:input_type -> ApproveVacancyRequest
	17, // 26: RecruitmentService.CloseVacancy:input_type -> CloseVacancyRequest
	18, // 27: RecruitmentService.RejectVacancy:input_type -> RejectVacancyRequest
	19, // 28: RecruitmentService.TakeInWorkVacancy:input_type -> TakeInWorkVacancyRequest
	22, // 29: RecruitmentService.GetVacancy:input_type -> GetVacancyRequest
	10, // 30: RecruitmentService.ConsiderCandidate:input_type -> ConsiderCandidateRequest
	20, // 31: RecruitmentService.ConsiderCandidateAnotherVacancy:input_type -> ConsiderCandidateAnotherVacancyRequest
	12, // 32: RecruitmentService.AcceptRecruitmentStage:input_type -> AcceptRecruitmentStageRequest
	13, // 33: RecruitmentService.DenyRecruitment:input_type -> DenyRecruitmentRequest
	24, // 34: RecruitmentService.GetRecruitment:input_type -> GetRecruitmentRequest
	26, // 35: RecruitmentService.ShowRecruitments:input_type -> ShowRecruitmentRequest
	5,  // 36: RecruitmentService.PostVacancy:output_type -> PostVacancyResponse
	7,  // 37: RecruitmentService.ShowVacancies:output_type -> ShowVacanciesResponse
	9,  // 38: RecruitmentService.SearchVacancies:output_type -> SearchVacanciesResponse
	15, // 39: RecruitmentService.ChangeVacancyPosition:output_type -> Empty
	15, // 40: RecruitmentService.ApproveVacancy:output_type -> Empty
	15, // 41: RecruitmentService.CloseVacancy:output_type -> Empty
	15, // 42: RecruitmentService.RejectVacancy:output_type -> Empty
	15, // 43: RecruitmentService.TakeInWorkVacancy:output_type -> Empty
	23, // 44: RecruitmentService.GetVacancy:output_type -> GetVacancyResponse
	11, // 45: RecruitmentService.ConsiderCandidate:output_type -> ConsiderCandidateResponse
	21, // 46: RecruitmentService.ConsiderCandidateAnotherVacancy:output_type -> ConsiderCandidateAnotherVacancyResponse
	15, // 47: RecruitmentService.AcceptRecruitmentStage:output_type -> Empty
	15, // 48: RecruitmentService.DenyRecruitment:output_type -> Empty
	25, // 49: RecruitmentService.GetRecruitment:output_type -> GetRecruitmentResponse
	27, // 50: RecruitmentService.ShowRecruitments:output_type -> ShowRecruitmentsResponse
	36, // [36:51] is the sub-list for method output_type
	21, // [21:36] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_grpc_service_recruitment_service_proto_init() }
func file_grpc_service_recruitment_service_proto_init() {
	if File_grpc_service_recruitment_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_service_recruitment_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostVacancyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostVacancyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowVacanciesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowVacanciesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchVacanciesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchVacanciesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsiderCandidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsiderCandidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptRecruitmentStageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DenyRecruitmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeVacancyPositionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApproveVacancyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseVacancyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RejectVacancyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TakeInWorkVacancyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsiderCandidateAnotherVacancyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsiderCandidateAnotherVacancyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVacancyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVacancyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecruitmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecruitmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowRecruitmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowRecruitmentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vacancy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Recruitment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageLineSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageLineItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_service_recruitment_service_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefuseReason); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_service_recruitment_service_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_service_recruitment_service_proto_goTypes,
		DependencyIndexes: file_grpc_service_recruitment_service_proto_depIdxs,
		EnumInfos:         file_grpc_service_recruitment_service_proto_enumTypes,
		MessageInfos:      file_grpc_service_recruitment_service_proto_msgTypes,
	}.Build()
	File_grpc_service_recruitment_service_proto = out.File
	file_grpc_service_recruitment_service_proto_rawDesc = nil
	file_grpc_service_recruitment_service_proto_goTypes = nil
	file_grpc_service_recruitment_service_proto_depIdxs = nil
}
