// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: recruitment-service/recruitment-service.proto

package recruitment_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostVacancyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PostVacancyRequest) Reset() {
	*x = PostVacancyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recruitment_service_recruitment_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostVacancyRequest) ProtoMessage() {}

func (x *PostVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_service_recruitment_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostVacancyRequest.ProtoReflect.Descriptor instead.
func (*PostVacancyRequest) Descriptor() ([]byte, []int) {
	return file_recruitment_service_recruitment_service_proto_rawDescGZIP(), []int{0}
}

type PostVacancyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PostVacancyResponse) Reset() {
	*x = PostVacancyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recruitment_service_recruitment_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostVacancyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostVacancyResponse) ProtoMessage() {}

func (x *PostVacancyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_service_recruitment_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostVacancyResponse.ProtoReflect.Descriptor instead.
func (*PostVacancyResponse) Descriptor() ([]byte, []int) {
	return file_recruitment_service_recruitment_service_proto_rawDescGZIP(), []int{1}
}

var File_recruitment_service_recruitment_service_proto protoreflect.FileDescriptor

var file_recruitment_service_recruitment_service_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x14, 0x0a, 0x12, 0x50, 0x6f, 0x73, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x50, 0x6f, 0x73, 0x74, 0x56, 0x61, 0x63,
	0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x50, 0x0a, 0x12,
	0x52, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x50, 0x6f, 0x73, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63,
	0x79, 0x12, 0x13, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x56, 0x61, 0x63, 0x61, 0x6e, 0x63, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x56, 0x61, 0x63,
	0x61, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x4c,
	0x5a, 0x4a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x79,
	0x65, 0x72, 0x6b, 0x76, 0x2f, 0x67, 0x6f, 0x2d, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x2f, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recruitment_service_recruitment_service_proto_rawDescOnce sync.Once
	file_recruitment_service_recruitment_service_proto_rawDescData = file_recruitment_service_recruitment_service_proto_rawDesc
)

func file_recruitment_service_recruitment_service_proto_rawDescGZIP() []byte {
	file_recruitment_service_recruitment_service_proto_rawDescOnce.Do(func() {
		file_recruitment_service_recruitment_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_recruitment_service_recruitment_service_proto_rawDescData)
	})
	return file_recruitment_service_recruitment_service_proto_rawDescData
}

var file_recruitment_service_recruitment_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_recruitment_service_recruitment_service_proto_goTypes = []interface{}{
	(*PostVacancyRequest)(nil),  // 0: PostVacancyRequest
	(*PostVacancyResponse)(nil), // 1: PostVacancyResponse
}
var file_recruitment_service_recruitment_service_proto_depIdxs = []int32{
	0, // 0: RecruitmentService.PostVacancy:input_type -> PostVacancyRequest
	1, // 1: RecruitmentService.PostVacancy:output_type -> PostVacancyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_recruitment_service_recruitment_service_proto_init() }
func file_recruitment_service_recruitment_service_proto_init() {
	if File_recruitment_service_recruitment_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_recruitment_service_recruitment_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostVacancyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recruitment_service_recruitment_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostVacancyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recruitment_service_recruitment_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recruitment_service_recruitment_service_proto_goTypes,
		DependencyIndexes: file_recruitment_service_recruitment_service_proto_depIdxs,
		MessageInfos:      file_recruitment_service_recruitment_service_proto_msgTypes,
	}.Build()
	File_recruitment_service_recruitment_service_proto = out.File
	file_recruitment_service_recruitment_service_proto_rawDesc = nil
	file_recruitment_service_recruitment_service_proto_goTypes = nil
	file_recruitment_service_recruitment_service_proto_depIdxs = nil
}
